Add junit collection to GHA

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -29,4 +29,10 @@ jobs:
             - name: Run tests
               run: |
                 export GIT_PYTHON_REFRESH=quiet
-                pytest -vs
+                pytest -vs --junit report.xml
+            
+            - name: Publish Test Report
+              uses: mikepenz/action-junit-report@v5
+              if: success() || failure() # always run even if the previous step fails
+              with:
+                report_paths: 'report.xml'
